from enum import Enum


class StageThreeTokenType(str, Enum):
    IDENTIFIER = "identifier"
    NEW_LINE = "\n"
    HYPHEN = "-"
    COMMA = ","
    SEMICOLON = ";"
    COLON = ":"
    OCTOTHORPE = "#"
    PERCENT = "%"
    PLUS = "+"
    ASTERISK = "*"
    FORWARD_SLASH = "/"
    BACKWARD_SLASH = "\\"
    ANGLED_LEFT = "<"
    ANGLED_RIGHT = ">"
    BRACKET_LEFT = "["
    BRACKET_RIGHT = "]"
    PAREN_LEFT = "("
    PAREN_RIGHT = ")"
    EQUALS = "="
    EXCLAMATION = "!"
    AMPERSAND = "&"
    PIPE = "|"
    FALSE = "false"
    TRUE = "true"
    IF = "if"
    FOR = "for"
    WHILE = "while"
    OR = "or"
    AND = "and"
    IN = "in"
    STRING = "STRING"
